name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push a branch
      pull-requests: write # To create a PR from that branch
    steps:
      - uses: actions/checkout@v4
      # - uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      # - run: (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)
      - run: wget https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz
      - run: tar zxvf mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz
      - run: mkdir -p $HOME/.cargo/bin && mv mdbook $HOME/.cargo/bin/mdbook
      - run: mdbook build && mdbook test # In case of custom book path: mdbook build path/to/mybook && mdbook test path/to/mybook
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: book # The folder the action should deploy.
